import React, { useState, useEffect, useCallback } from "react";

// ─────────────────────────────────────────────────────────────────
// TestPanel — Forge Test Results Viewer
//
// Fetches /test-results.json (generated by: forge test --json)
// and displays a live dashboard of pass/fail per contract group.
//
// Refresh by clicking "Run Tests" (triggers re-fetch of the file,
// which should be regenerated by the run-tests.sh script).
// ─────────────────────────────────────────────────────────────────

// ─── Helpers ─────────────────────────────────────────────────────

function stripContractPath(raw) {
  // "test/unit/XenorizeTest.t.sol:ContractName" → "ContractName"
  return raw.includes(":") ? raw.split(":").pop() : raw;
}

function formatDuration(d) {
  if (!d) return "";
  const ms = (d.secs || 0) * 1000 + Math.round((d.nanos || 0) / 1e6);
  return ms < 1000 ? `${ms} ms` : `${(ms / 1000).toFixed(2)} s`;
}

function parseKind(result) {
  if (!result.kind) return { type: "Unit", runs: null };
  if (result.kind.Fuzz)      return { type: "Fuzz", runs: result.kind.Fuzz.runs };
  if (result.kind.Invariant) return { type: "Invariant", runs: result.kind.Invariant.runs };
  return { type: "Unit", runs: null };
}

// ─── Sub-components ───────────────────────────────────────────────

function SummaryBar({ total, passed, failed, duration, fetchedAt }) {
  const pct = total > 0 ? Math.round((passed / total) * 100) : 0;

  return (
    <div className="test-summary-bar">
      <div className="test-summary-left">
        <span className={`test-pill ${failed === 0 ? "pill-pass" : "pill-fail"}`}>
          {failed === 0 ? "✓ All Passing" : `✗ ${failed} Failing`}
        </span>
        <span className="test-stat">{passed}/{total} passed</span>
        <span className="test-stat">{pct}%</span>
        {duration && <span className="test-stat">{duration}</span>}
      </div>
      <div className="test-summary-right">
        {fetchedAt && (
          <span className="test-fetched-at">
            last run: {fetchedAt.toLocaleTimeString()}
          </span>
        )}
      </div>
    </div>
  );
}

function ProgressBar({ passed, total }) {
  const pct = total > 0 ? (passed / total) * 100 : 0;
  return (
    <div className="test-progress-track">
      <div
        className={`test-progress-fill ${passed === total ? "fill-pass" : "fill-fail"}`}
        style={{ width: `${pct}%` }}
      />
    </div>
  );
}

function TestRow({ name, result, expanded }) {
  const { type, runs } = parseKind(result);
  const pass = result.status === "Success";

  return (
    <tr className={`test-row ${pass ? "row-pass" : "row-fail"}`}>
      <td className="test-icon-cell">{pass ? "✓" : "✗"}</td>
      <td className="test-name-cell">
        <span className="test-name">{name}</span>
        {result.reason && (
          <span className="test-reason"> — {result.reason}</span>
        )}
      </td>
      <td>
        <span className={`test-badge badge-${type.toLowerCase()}`}>{type}</span>
        {runs != null && <span className="test-runs">{runs.toLocaleString()} runs</span>}
      </td>
      <td className="test-duration-cell">{formatDuration(result.duration)}</td>
    </tr>
  );
}

function ContractBlock({ contractPath, data, defaultOpen }) {
  const [open, setOpen] = useState(defaultOpen);
  const name = stripContractPath(contractPath);
  const results = Object.entries(data.test_results || {});
  const passed  = results.filter(([, r]) => r.status === "Success").length;
  const failed  = results.length - passed;
  const allPass = failed === 0;

  return (
    <div className={`contract-block ${allPass ? "block-pass" : "block-fail"}`}>
      <button className="contract-header" onClick={() => setOpen((o) => !o)}>
        <span className="contract-chevron">{open ? "▾" : "▸"}</span>
        <span className={`contract-dot ${allPass ? "dot-pass" : "dot-fail"}`} />
        <span className="contract-name">{name}</span>
        <span className="contract-counts">
          <span className="count-pass">{passed} pass</span>
          {failed > 0 && <span className="count-fail"> · {failed} fail</span>}
        </span>
        <span className="contract-time">{formatDuration(data.duration)}</span>
      </button>

      {open && (
        <table className="test-table">
          <tbody>
            {results.map(([testName, result]) => (
              <TestRow key={testName} name={testName} result={result} />
            ))}
          </tbody>
        </table>
      )}
    </div>
  );
}

// ─── Main Component ───────────────────────────────────────────────

export default function TestPanel() {
  const [raw,       setRaw]       = useState(null);
  const [loading,   setLoading]   = useState(true);
  const [error,     setError]     = useState(null);
  const [fetchedAt, setFetchedAt] = useState(null);
  const [filter,    setFilter]    = useState("all"); // "all" | "fail" | "fuzz" | "unit"
  const [search,    setSearch]    = useState("");

  const load = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      // Cache-bust so we always get the latest file after re-running tests
      const res = await fetch(`/test-results.json?t=${Date.now()}`);
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const json = await res.json();
      setRaw(json);
      setFetchedAt(new Date());
    } catch (e) {
      setError(e.message);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => { load(); }, [load]);

  // ── Compute aggregates ──────────────────────────────────────────
  const contracts = raw ? Object.entries(raw) : [];

  let total    = 0;
  let passed   = 0;
  let totalMs  = 0;

  contracts.forEach(([, v]) => {
    const results = Object.values(v.test_results || {});
    total   += results.length;
    passed  += results.filter((r) => r.status === "Success").length;
    totalMs += (v.duration?.secs || 0) * 1000 + Math.round((v.duration?.nanos || 0) / 1e6);
  });

  const failed    = total - passed;
  const durationStr = totalMs < 1000 ? `${totalMs} ms` : `${(totalMs / 1000).toFixed(2)} s`;

  // ── Filtering ───────────────────────────────────────────────────
  const filtered = contracts
    .map(([contractPath, data]) => {
      const results = Object.entries(data.test_results || {});
      const filteredResults = results.filter(([name, r]) => {
        const { type } = parseKind(r);
        if (filter === "fail" && r.status !== "Failure") return false;
        if (filter === "fuzz" && type !== "Fuzz")        return false;
        if (filter === "unit" && type !== "Unit")        return false;
        if (search && !name.toLowerCase().includes(search.toLowerCase())) return false;
        return true;
      });
      return [contractPath, { ...data, test_results: Object.fromEntries(filteredResults) }];
    })
    .filter(([, data]) => Object.keys(data.test_results).length > 0);

  // ── Render ──────────────────────────────────────────────────────
  return (
    <div className="test-panel">
      <div className="test-panel-header">
        <div className="test-panel-title">
          <span className="test-panel-icon">🧪</span>
          <h2>Forge Test Suite</h2>
          <span className="test-contract-count">{contracts.length} contracts</span>
        </div>

        <div className="test-panel-actions">
          <div className="test-filter-group">
            {["all", "fail", "fuzz", "unit"].map((f) => (
              <button
                key={f}
                className={`test-filter-btn ${filter === f ? "filter-active" : ""}`}
                onClick={() => setFilter(f)}
              >
                {f === "all"  && "All"}
                {f === "fail" && `✗ Failed${failed > 0 ? ` (${failed})` : ""}`}
                {f === "fuzz" && "Fuzz"}
                {f === "unit" && "Unit"}
              </button>
            ))}
          </div>
          <input
            className="test-search"
            placeholder="Search tests…"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
          />
          <button
            className="btn btn-primary test-refresh-btn"
            onClick={load}
            disabled={loading}
            title="Re-fetch test-results.json (run forge test --json first)"
          >
            {loading ? "⟳ Loading…" : "⟳ Refresh"}
          </button>
        </div>
      </div>

      {!loading && !error && raw && (
        <>
          <SummaryBar
            total={total} passed={passed} failed={failed}
            duration={durationStr} fetchedAt={fetchedAt}
          />
          <ProgressBar passed={passed} total={total} />
        </>
      )}

      {loading && (
        <div className="test-loading">Loading test results…</div>
      )}

      {error && (
        <div className="test-error-banner">
          <strong>Could not load test-results.json</strong> — {error}
          <br />
          <small>Run <code>./run-tests.sh</code> from the xenorize directory, then click Refresh.</small>
        </div>
      )}

      {!loading && !error && filtered.length === 0 && (
        <div className="test-empty">No tests match the current filter.</div>
      )}

      {!loading && !error && (
        <div className="contract-list">
          {filtered.map(([contractPath, data], i) => (
            <ContractBlock
              key={contractPath}
              contractPath={contractPath}
              data={data}
              defaultOpen={i === 0 || failed > 0}
            />
          ))}
        </div>
      )}

      <div className="test-panel-footer">
        <span>Generated by <code>forge test --json</code></span>
        <span>·</span>
        <span>Run <code>./run-tests.sh</code> to refresh</span>
      </div>
    </div>
  );
}
