[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
script = "script"
solc_version = "0.8.26"
optimizer = true
optimizer_runs = 1_000_000
via_ir = true
fuzz = { runs = 10_000 }
invariant = { runs = 1_000, depth = 100 }

[profile.ci]
fuzz = { runs = 50_000 }
invariant = { runs = 5_000, depth = 500 }

[profile.lite]
optimizer = false
fuzz = { runs = 100 }

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
int_types = "long"
quote_style = "double"
number_underscore = "thousands"

[rpc_endpoints]
arbitrum_sepolia = "${ARBITRUM_SEPOLIA_RPC}"
arbitrum         = "${ARBITRUM_RPC}"
base             = "${BASE_RPC}"
mainnet          = "${MAINNET_RPC}"

[etherscan]
arbitrum_sepolia = { key = "${ARBISCAN_API_KEY}", url = "https://api-sepolia.arbiscan.io/api" }
arbitrum         = { key = "${ARBISCAN_API_KEY}" }
base             = { key = "${BASESCAN_API_KEY}" }